<a href="https://colab.research.google.com/github/taufeeque9/FMDS/blob/main/Untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Loading the data**


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# New section

In [ ]:
# In read_csv() function, we have passed the raw data link at github
data = pd.read_csv('https://raw.githubusercontent.com/tuff96/Malware-detection-using-Machine-Learning/master/data.csv', sep = '|')
print(data.head())
#separating input and output variables
X = data.drop(['Name', 'md5', 'legitimate'], axis = 1)
y = data['legitimate']

                                Name                               md5  \
0  Windows.Internal.Shell.Broker.dll  09e83f1d1c99ad33009dbe6fb129c2d9   
1                        hidserv.dll  3030f19c6a73367d6d5eedd157f5d01a   
2         DmApiSetExtImplDesktop.dll  8271846f8f5dd1cfddaa957b1b9da1a2   
3               FSResizerSetup27.exe  5802b4215566bb9593a736e945a28e99   
4                      asc-setup.exe  8cb1fb45489d065720285deeccbacd98   

   Machine  SizeOfOptionalHeader  Characteristics  MajorLinkerVersion  \
0    34404                   240             8226                  14   
1    34404                   240             8226                  14   
2    34404                   240             8226                  14   
3      332                   224              271                   6   
4      332                   224            33167                   2   

   MinorLinkerVersion  SizeOfCode  SizeOfInitializedData  \
0                  12      779776                 253952

**Understanding data**


In [ ]:
data.head()

Name                               md5  \
0  Windows.Internal.Shell.Broker.dll  09e83f1d1c99ad33009dbe6fb129c2d9   
1                        hidserv.dll  3030f19c6a73367d6d5eedd157f5d01a   
2         DmApiSetExtImplDesktop.dll  8271846f8f5dd1cfddaa957b1b9da1a2   
3               FSResizerSetup27.exe  5802b4215566bb9593a736e945a28e99   
4                      asc-setup.exe  8cb1fb45489d065720285deeccbacd98   

   Machine  SizeOfOptionalHeader  Characteristics  MajorLinkerVersion  \
0    34404                   240             8226                  14   
1    34404                   240             8226                  14   
2    34404                   240             8226                  14   
3      332                   224              271                   6   
4      332                   224            33167                   2   

   MinorLinkerVersion  SizeOfCode  SizeOfInitializedData  \
0                  12      779776                 253952   
1                  12       21504                  13312   
2                  12       33792                  27648   
3                   0       23552                 164864   
4                  25       87040                  71680   

   SizeOfUninitializedData  ...  ResourcesNb  ResourcesMeanEntropy  \
0                        0  ...            2              3.072050   
1                        0  ...            3              3.056204   
2                        0  ...            1              3.466474   
3                     1024  ...            9              3.032143   
4                        0  ...           19              4.402265   

   ResourcesMinEntropy  ResourcesMaxEntropy  ResourcesMeanSize  \
0             2.706833             3.437268         604.000000   
1             2.709457             3.465499         515.333333   
2             3.466474             3.466474         980.000000   
3             1.971335             5.102472         363.444444   
4             2.699131             6.600332        3275.473684   

   ResourcesMinSize  ResourcesMaxSize  LoadConfigurationSize  \
0               200              1008                    256   
1               200               932                    256   
2               980               980                    256   
3                34               744                      0   
4                16             33512                      0   

   VersionInformationSize  legitimate  
0                      16           1  
1                      16           1  
2                      16           1  
3                       0           1  
4                      15           1  

[5 rows x 57 columns]

In [ ]:
#shape of training and test data
print("Shape: ", X.shape, "Dimension: ", X.ndim)
print("Shape: ", y.shape, "Dimension: ", y.ndim)

Shape:  (10539, 54) Dimension:  2
Shape:  (10539,) Dimension:  1


Splitting of data into test data and train data

In [ ]:
# import train_test_split
from sklearn.model_selection import train_test_split

In [ ]:
# split the data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state = 42)

# X_train: independent/input feature data for training the model
# y_train: dependent/output feature data for training the model
# X_test: independent/input feature data for testing the model; will be used to predict the output values
# y_test: original dependent/output values of X_test; We will compare this values with our predicted values to check the performance of our built model.
 
# test_size = 0.30: 30% of the data will go for test set and 70% of the data will go for train set
# random_state = 42: this will fix the split i.e. there will be same split for each time you run the code

**Building model**


In [ ]:
# import Logistic Regression from sklearn.linear_model
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression(max_iter=50000)

In [ ]:
# Fit the model
model.fit(X_train, y_train)

LogisticRegression(max_iter=50000)

**Prediction**

In [ ]:
predictions = model.predict(X_test)


In [ ]:
y_test.values

array([1, 1, 0, ..., 0, 0, 1])

In [ ]:
print(predictions)

[1 0 0 ... 0 0 0]


**Model Performance**

In [ ]:
# The confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions) 

array([[2056,   34],
       [ 106,  966]])

In [ ]:
tn, fp, fn, tp = confusion_matrix(y_test, predictions).ravel()   # ravel() will convert the 2D numpy array into 1D.
print(tn, fp, fn, tp)

2056 34 106 966


In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test, predictions)

0.9557242251739405